FROM python:3.11-slim
# TODO: add install, copy, expose, entrypoints

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . . 

EXPOSE 8000

CMD ["python", "src/app.py"]

ENTRYPOINT ["curl"]