name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Python
      # - name: Install deps
      # - name: Run tests
      # - name: Build Docker
