name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.12 python3.12-venv python3.12-dev
          python3.12 --version

      - name: Set up Poetry for dependency management
        run: |
          sudo apt update
          sudo apt install pipx
          pipx install poetry

      - name: Install deps and activate virtual env
        run: | 
          poetry install
          poetry shell

      - name: Run tests
        run: |
          python -m pytest

      #- name: Build Docker


